dist: trusty
language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
install:
    - pip install -r requirements.txt
    - cp Makefile.appconfig.example Makefile.appconfig
    - cp config.py.example config.py
script:
    - make tests
